version: '3.7'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: sardine
      MONGO_INITDB_ROOT_PASSWORD: coolDuck737
      MONGO_INITDB_DATABASE: housing
    ports:
      - 27017:27017
    volumes:
      - "dbconfig:/data/configdb"
      - "dbdata:/data/db"
    #command: ["-f", "/etc/mongod.conf"]
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:5000
volumes:
  dbdata:
  dbconfig: